---
init_dest_dir: /lib/systemd/system/
ipxe_dir: /usr/lib/ipxe/
ironic_rootwrap_dir: /usr/local/bin/
mysql_service_name: mysql
tftp_service_name: tftpd-hpa
efi_distro: "{{ ansible_facts['distribution'] | lower }}"
grub_efi_package: grub-efi-amd64-signed
grub_efi_binary: /usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed
shim_efi_package: shim-signed
shim_efi_binary: "/usr/lib/shim/shimx64.efi.signed{{ '.latest' if ansible_distribution == 'Ubuntu' else '' }}"
required_packages:
  - mariadb-server
  - python3-dev
  - libffi-dev
  - libxslt1-dev
  - libssl-dev
  - libxml2-dev
  - ipxe
  - parted
  - ipmitool
  - iptables
  - bsdmainutils
  - psmisc
  - wget
  - genisoimage
  - qemu-utils
  - uuid-runtime
  - curl
  - socat
  - gcc
  - dnsmasq
  - isolinux
  - dosfstools
# NOTE(TheJulia): The above entry for dnsmasq must be the last entry in the
# package list as the installation causes name resolution changes that can
# temporarily block packages following it while the system is being
# reconfigured. See: https://review.opendev.org/#/c/223813
