---
init_dest_dir: /usr/lib/systemd/system/
ipxe_dir: /usr/share/ipxe/
ipxe_efi_binary: ipxe-snponly-x86_64.efi
ironic_rootwrap_dir: /usr/bin/
mysql_service_name: mariadb
tftp_service_name: tftp
efi_distro: "{{ ansible_facts['distribution'] | lower }}"
grub_efi_package: grub2-efi-x64
grub_efi_binary: "/boot/efi/EFI/{{ efi_distro }}/grubx64.efi"
shim_efi_package: shim-x64
shim_efi_binary: "/boot/efi/EFI/{{ efi_distro }}/shimx64.efi"
required_packages:
  - mariadb-server
  - dnsmasq
  - python3-devel
  - libffi-devel
  - libxslt-devel
  - openssl-devel
  - libxml2-devel
  - ipxe-bootimgs
  - parted
  - ipmitool
  - psmisc
  - wget
  - xorriso
  - kernel-tools
  - qemu-img
  - python3-libselinux
  - python3-policycoreutils
  - gcc
  - socat
  - firewalld
  - python3-firewall
  - syslinux-nonlinux
  - dosfstools
