# Copyright (c) 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Shade - Retrieving library from git.openstack.org"
  command: git clone https://review.openstack.org/openstack-infra/shade chdir=/opt/stack creates=/opt/stack/shade
  when: ci_testing == false
- name: "Shade - Checking out master branch"
  command: git checkout -f master chdir=/opt/stack/shade
  when: ci_testing == false
- name: "Shade - Resetting local repository"
  command: git reset --hard master chdir=/opt/stack/shade
  when: ci_testing == false
- name: "Shade - Resyncing local repository"
  command: git pull --ff-only chdir=/opt/stack/shade
  when: ci_testing == false
- name: "Shade - Installing patched shade library."
  command: pip install -I --force-reinstall /opt/stack/shade
