---
init_dest_dir: /lib/systemd/system/
nginx_user: www-data
mysql_service_name: mysql
required_packages:
  - mariadb-server
  - python-dev
  - python-mysqldb
  - python-configparser
  - libffi-dev
  - libxslt1-dev
  - libssl-dev
  - libxml2-dev
  - nginx
  - uwsgi
  - uwsgi-core
  # - python-django-uwsgi - This may not be needed
  - uwsgi-plugin-python
