---
init_dest_dir: /usr/lib/systemd/system/
nginx_user: nginx
virt_group: libvirt
mysql_service_name: mariadb
required_packages:
  - mariadb-server
  - python3-devel
  - python3-PyMySQL
  - python3-iniparse
  - python3-libselinux
  - python3-policycoreutils
  - libffi-devel
  - libxslt-devel
  - openssl-devel
  - libxml2-devel
  - nginx
