---
sgabios_dir: /usr/share/qemu/
libvirt_service_name: libvirt-bin
required_packages:
 - libvirt-bin
 - qemu-utils
 - qemu-kvm
 - qemu-system-x86
 - sgabios
 - python-libvirt
 - python-lxml
 - pkg-config
 - libvirt-dev
