---
sgabios_dir: /usr/share/sgabios/
libvirt_service_name: libvirtd
required_packages:
 - qemu-img
 - qemu-kvm
 - qemu-system-x86
 - sgabios-bin
 - libvirt
 - libvirt-client
 - libvirt-daemon
 - pkgconfig
 - libvirt-devel
 - python3-libselinux
 - edk2-ovmf
