---
sgabios_dir: /usr/share/sgabios/
libvirt_service_name: libvirtd
required_packages:
 - gcc-c++
 - qemu-tools
 - qemu-kvm
 - qemu-x86
 - qemu-sgabios
 - libvirt
 - libvirt-client
 - libvirt-daemon
 - libxslt-devel
 - libxml2-devel
 - pkg-config
 - libvirt-devel
 - qemu-ovmf-x86_64
 - ebtables
 - dnsmasq
