---
sgabios_dir: /usr/share/sgabios/
libvirt_service_name: libvirtd
required_packages:
 - gcc-c++
 - qemu-img
 - kernel-tools
 - qemu-kvm
 - qemu-kvm-common
 - qemu-system-x86
 - sgabios-bin
 - libvirt
 - libvirt-client
 - libvirt-daemon
 - pkgconfig
 - libvirt-devel
 - libxslt-devel
 - libxml2-devel
 - edk2-ovmf
