---
init_dest_dir: /usr/lib/systemd/system/
ipxe_dir: /usr/share/ipxe
ipxe_full_binary: ipxe.lkrn
ipxe_efi_binary: ipxe-x86_64.efi
ironic_rootwrap_dir: /usr/bin/
nginx_user: nginx
mysql_service_name: mysql
tftp_service_name: tftp
required_packages:
  - python-selinux
  - mariadb-server
  - dnsmasq
  - python-devel
  - python-iniparse
  - libffi-devel
  - libxslt-devel
  - openssl-devel
  - libxml2-devel
  - ipxe-bootimgs
  - qemu-ipxe
  - tftp
  - xinetd
  - parted
  - ipmitool
  - psmisc
  - nginx
  - wget
  - mkisofs
  - kpartx
  - qemu-tools
  - policycoreutils-python
  - dpkg
  - iptables
  - tar
  - curl
  - socat
  - python-pip
  - gcc
  - python-PyMySQL
  - apache2-utils
  - syslinux
iscsi_required_packages:
  - open-iscsi
  - gptfdisk
  - dosfstools
