---
init_dest_dir: /usr/lib/systemd/system/
ipxe_dir: /usr/share/ipxe/
ipxe_full_binary: ipxe.lkrn
ipxe_efi_binary: ipxe-x86_64.efi
ironic_rootwrap_dir: /usr/bin/
mysql_service_name: mariadb
tftp_service_name: tftp
required_packages:
  - mariadb-server
  - dnsmasq
  - python3-devel
  - python3-PyMySQL
  - python3-iniparse
  - libffi-devel
  - libxslt-devel
  - openssl-devel
  - libxml2-devel
  - ipxe-bootimgs
  - parted
  - ipmitool
  - psmisc
  - wget
  - genisoimage
  - kpartx
  - kernel-tools
  - qemu-img
  - python3-libselinux
  - python3-policycoreutils
  - gcc
  - python3-pip
  - socat
  - firewalld
  - python3-firewall
  - httpd-tools
  - syslinux-nonlinux
  - grub2-efi-x64
  - shim-x64
  - dosfstools
