---
init_dest_dir: /usr/lib/systemd/system/
ipxe_dir: /usr/share/ipxe/
ipxe_full_binary: ipxe.lkrn
ironic_rootwrap_dir: /usr/bin/
nginx_user: nginx
mysql_service_name: mariadb
tftp_service_name: tftp
efi_distro: fedora
grub_efi_binary: /boot/efi/EFI/fedora/grubx64.efi
required_packages:
  - dnsmasq
  - firewalld
  - gcc
  - genisoimage
  - grub2-efi-x64
  - httpd-tools
  - ipmitool
  - ipxe-bootimgs
  - kpartx
  - libffi-devel
  - libxml2-devel
  - libxslt-devel
  - mariadb-server
  - nginx
  - openssl-devel
  - parted
  - policycoreutils-python-utils
  - psmisc
  - python3-devel
  - python3-iniparse
  - python3-libselinux
  - python3-policycoreutils
  - python3-PyMySQL
  - qemu-img
  - qemu-kvm
  - shim-x64
  - socat
  - syslinux-nonlinux
  - tftp-server
  - wget
  - xinetd
iscsi_required_packages:
  - iscsi-initiator-utils
  - gdisk
  - dosfstools
