- hosts: all
  tasks:
    - shell:
        cmd: bash scripts/test-bifrost.sh
        chdir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/bifrost'].src_dir }}"
      environment:
        BUILD_IMAGE: "{{ build_image | default(false) | bool | lower }}"
        CLI_TEST: "{{ cli_test | default(false) | bool | lower }}"
        ENABLE_KEYSTONE: "{{ enable_keystone | default(false) | bool | lower }}"
        LOG_LOCATION: "{{ ansible_user_dir }}/logs"
        UPPER_CONSTRAINTS_FILE: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/requirements'].src_dir }}/upper-constraints.txt"
        WORKSPACE: "{{ ansible_user_dir }}/src/opendev.org"
        USE_DHCP: "{{ use_dhcp | default(false) | bool | lower }}"
        ENABLE_VENV: "{{ use_venv | default(true) | bool | lower }}"
        ZUUL_BRANCH: "{{ zuul.branch }}"
        BOOT_MODE: "{{ boot_mode | default('') }}"
