---
sgabios_dir: /usr/share/qemu/
libvirt_service_name: libvirtd
required_packages:
 - g++
 - libvirt-daemon-system
 - libxslt1-dev
 - libxml2-dev
 - qemu-utils
 - qemu-kvm
 - qemu-system-x86
 - qemu-system-data
 - pkg-config
 - libvirt-dev
 - ovmf
 - ebtables
 - dnsmasq

ovs_packages:
 - openvswitch-switch
 - python3-openvswitch
ovs_service_name: openvswitch-switch
