---
sgabios_dir: /usr/share/sgabios/
libvirt_service_name: libvirtd
required_packages:
 - gcc-c++
 - qemu-img
 - kernel-tools
 - qemu-kvm
 - "{{ 'sgabios-bin' if ansible_distribution_version | int == 9 else '' }}"
 - libvirt
 - libvirt-client
 - libvirt-daemon
 - libvirt-daemon-kvm
 - python3-libvirt
 - python3-libselinux
 - libxslt-devel
 - libxml2-devel
 - edk2-ovmf

ovs_packages:
 # TODO(alegacy): Update versioned package names periodically
 - openvswitch3.5
 - python3-openvswitch3.5
ovs_service_name: openvswitch

test_vm_emulator: "/usr/libexec/qemu-kvm"
